---
title: Welcome to R Fridays!
author: ''
date: '2019-07-03'
slug: hello-tuftesque
categories: []
tags: []
excerpt: "Start here if you are new to R Fridays"
---

# Getting Started

Welcome to R Fridays! The goal of R Fridays is to provide a group environment for solving problems in biology/biochemistry data analysis (best practices for statistics, visualization, etc.). Bring data your own data and questions, or just come to learn from problems that others are working on.

Before your first R Friday, make sure that you have R and RStudio installed on your machine. 

## R: 

To check if R is installed on your machine, open up a command line (terminal) window and type 

```
R --version
```

The above should produce the following:

```{bash}
R --version
```


If this doesn't work, you can download R [here](http://www.r-project.org).

## RStudio: 

RStudio is an integrate development environment (IDE) that simplifies writing and running R code. You can download RStudio Desktop [here](https://www.rstudio.com/products/rstudio/download/).

## Key Resources

These two online textbooks are fantastic resources for learning best practices in statistics and R programming.

 - [Modern Statistics for Modern Biology](http://web.stanford.edu/class/bios221/book/) by Susan Holmes and Wolfgang Huber
 - [R for Data Science](https://r4ds.had.co.nz) by Garret Grolemund and Hadley Wickham

If you are new to R or statistics in R, we recommend reading at least the introduction of these books before your first R Friday. In total, the reading is ~ 20 minutes.

_The readings are suggested starting points if you are new to R or statistics in R. Feel free to skip if they are review for you. _

# Wrap-Up

That's pretty much it. If any of the above was confusing to you please don't hesitate to email [me](https://saraharcos.github.io/contact.html) or ping me on [twitter](https://www.twitter.com/sarah_arcos).